# 服务基础路径，存放本地数据库以及配置文件等
# 目录结构：
#  root/
#    |- bin
#     \- voucher
#     \- config.toml
#    |- certs
#     \- server.pem
#     \- server.key
#     \- client.pem
#     \- client.key
#     \- dev01.pem
#     \- dev01.key
#     \- ...
#    |- db
#    |- scripts
#     \- client-cert.sh
#     \- server-cert.sh
basedir = "/Users/admin/Work/src/github.com/boxproject/voucher/build/"

[agentservice]
# 服务名称
name = "voucher"
# 服务别名
alias = "server1"
companionname = "companion"
#http
ipandport = "192.168.199.150:9092"
pattern = "/addkey"
# rpc
rpcapi = "127.0.0.1:50502"
# 如果不填该参数，默认查找 ${basedir}/certs/${name}.pem
clientcert = "/Users/admin/ssl/client.pem"
# 如果不填该参数，默认查找 ${basedir}/certs/${name}.key
clientkey = "/Users/admin/ssl/client.key"

[secret]
# 服务器端密钥字节数
secretLength = 40
# 初始化时下载客户端证书一次性密码字节数
passLength = 8
# 授权APP的数量
appNum = 2

[database]
# 如果不提供该参数，默认为 ${basedir}/db
# filePath = ""
# 如果不提供该参数，默认是16
cache = 128
# 如果不提供该参数，默认是16
openFiles = 16
# 如果不提供该参数，默认是 BOX
# prefix = "BOX"

[log]
# DEBUG/INFO/ERROR/FATAL/WARN
level = "DEBUG"
# json/console
encoding = "console"
# 日志存储位置. 如果不提供，默认为 ${basedir}/log
# logPath = ""

# 提供手机APP客户端证书下载
[service]
port = 8966
ip = "0.0.0.0"

# 提供手机端API服务
[api]
port = 9867
ip = "0.0.0.0"

# 以太坊公链节点
[ethereum]
scheme = "ws://127.0.0.1:8546"
delayedBlocks = 0
cursorBlocks = 15900
retries = 10
accountPoolSize = 2
blockNoFilePath = "/Users/admin/Work/src/github.com/boxproject/voucher/blockno.txt"
nonceFilePath = "/Users/admin/Work/src/github.com/boxproject/voucher/nonce.txt"

# 测试环境，私链节点1
[[node]]
name = "dev02"
rpcapi = "127.0.0.1:50502"
# 如果不填该参数，默认查找 ${basedir}/certs/${name}.pem
clientcert = "/Users/admin/ssl/client.pem"
# 如果不填该参数，默认查找 ${basedir}/certs/${name}.key
clientkey = "/Users/admin/ssl/client.key"

# bitcoin node
[bitcoin]
type = "regtest"
host = "localhost:8332"
rpcuser="admin"
rpcpass="51318c0c86d5b51b3beffbc02b724e"
blockNoFilePath = "/Users/admin/Work/src/github.com/boxproject/voucher/btcBlockno.txt"
confirmations=6
